use sucos_vendas;

/*quantidae por sabor vendida em 2016*/

select * FROM
(select TP.SABOR,year(NF.DATA_VENDA) AS ANO, sum(INF.QUANTIDADE) AS QUANTIDADE_POR_SABOR from tabela_de_produtos TP 
inner join 
itens_notas_fiscais INF 
on INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
inner join
notas_fiscais NF 
on NF.NUMERO = INF.NUMERO
where year(NF.DATA_VENDA) = 2016
group by TP.SABOR, year(NF.data_venda)) as VENDA_SABOR
 INNER join
(select year(NF.DATA_VENDA) AS ANO, sum(INF.QUANTIDADE) AS QUANTIDADE_TOTAL from tabela_de_produtos TP 
inner join 
itens_notas_fiscais INF 
on INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
inner join
notas_fiscais NF 
on NF.NUMERO = INF.NUMERO
where year(NF.DATA_VENDA) = 2016
group by year(NF.data_venda)) AS VENDAS_TOTAL
ON VENDA_SABOR.ANO = VENDAS_TOTAL.ANO;




select VENDA_SABOR.SABOR, VENDA_SABOR.ANO, VENDA_SABOR.QUANTIDADE_POR_SABOR,
round((VENDA_SABOR.QUANTIDADE_POR_SABOR/VENDAS_TOTAL.QUANTIDADE_TOTAL) * 100, 2) AS PARTICIPACAO
 FROM 
(select TP.SABOR,year(NF.DATA_VENDA) AS ANO, sum(INF.QUANTIDADE) AS QUANTIDADE_POR_SABOR from tabela_de_produtos TP 
inner join 
itens_notas_fiscais INF 
on INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
inner join
notas_fiscais NF 
on NF.NUMERO = INF.NUMERO
where year(NF.DATA_VENDA) = 2016
group by TP.SABOR, year(NF.data_venda)) as VENDA_SABOR
 INNER join
(select year(NF.DATA_VENDA) AS ANO, sum(INF.QUANTIDADE) AS QUANTIDADE_TOTAL from tabela_de_produtos TP 
inner join 
itens_notas_fiscais INF 
on INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
inner join
notas_fiscais NF 
on NF.NUMERO = INF.NUMERO
where year(NF.DATA_VENDA) = 2016
group by year(NF.data_venda)) AS VENDAS_TOTAL
ON VENDA_SABOR.ANO = VENDAS_TOTAL.ANO
order by VENDA_SABOR.QUANTIDADE_POR_SABOR DESC;

SELECT VENDA_TAMANHO.TAMANHO, VENDA_TAMANHO.ANO, VENDA_TAMANHO.QUANTIDADE,
ROUND((VENDA_TAMANHO.QUANTIDADE/VENDA_TOTAL.QUANTIDADE) * 100, 2) AS PARTICIPACAO FROM 
(SELECT TP.TAMANHO, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA_VENDA)) AS VENDA_TAMANHO
INNER JOIN 
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_TAMANHO.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_TAMANHO.QUANTIDADE DESC